#!/usr/bin/env bash
# Configure
# Nginx
# Serve a page
# colors

blue='\e[1;34m'
brown='\e[0;33m'
green='\e[1;32m'
reset='\033[0m'

echo -e "${blue}Updating and installing ${brown}Nginx${blue}.${reset}\n"
sudo apt-get update -y -qq && \
	 sudo apt-get install nginx -y

echo -e "\n${blue}Setting up some minor stuff.${reset}\n"

# starting
sudo service nginx start

# allowing nginx
sudo ufw allow 'Nginx HTTP'

# Give the user ownership
sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 755 /var/www

# Backup
cp /var/www/html/index.nginx-debian.html /var/www/html/index.nginx-debian.html.bckp

# Creating
echo -e "Hello World!" | dd status=none of=/var/www/html/index.nginx-debian.html

# Restarting
sudo service nginx restart

echo -e "\n${green}Completed.${reset} ✅\n"
